### PR TITLE
Lykhoyda/fix eslint warnings

### PR DESCRIPTION
**Pull request by Lykhoyda**
Fix eslint warnings related to unused variables and some more.
Refactored ConnectionDialog
## Related Issue Or Context

Closes: #<issue>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

### CODE REVIEW

**Comment by enemycnt** [comment]
I tried to connect my wallet while testing this PR, but I was not successful. However, I did not receive any error message in the console. Can you please verify if there are any issues with the connection?

**Comment by Lykhoyda** [comment]
> I tried to connect my wallet while testing this PR, but I was not successful. However, I did not receive any error message in the console. Can you please verify if there are any issues with the connection? @Lykhoyda

@enemycnt thank you for the review! It's fixed, in the next stories I will cover the project with more tests to avoid problems during refactoring

**Review by enemycnt — CHANGES_REQUESTED** [review]
Please, add a fix to the connection logic.

**Comment by Lykhoyda** [comment]
@enemycnt  I already added the fix, does it works on your side? My understanding is that connecting to metamask was breaking but not anymore. Any other problem I am missing? 
Screenshot 2023-03-10 at 11 08 51

**Review by enemycnt — APPROVED** [review]

**Pull request merged**
